services:
  web:
    container_name: PoetryNeomodelsFastapiTest-web
    build:
      context: .
      dockerfile: Dockerfile  # Default Dockerfile for the web service
    ports:
      - "8000:8000"
    extra_hosts:
      host.docker.internal: host-gateway  
    volumes:
      - .:/app
    env_file: .env  
    environment:
      - DATABASE_URL=bolt://neo4j:your_password_here@PoetryNeomodelsFastapiTest-neo4j:7687
      - PYTHONPATH=/app
    command: poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000  
    depends_on:
      - db-PoetryNeomodelsFastapiTest
      - neo4j-PoetryNeomodelsFastapiTest

  db-PoetryNeomodelsFastapiTest:
    container_name: PoetryNeomodelsFastapiTest-postgres
    image: postgres:13
    environment:
      POSTGRES_DB: cvosocial
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  neo4j-PoetryNeomodelsFastapiTest:
    container_name: PoetryNeomodelsFastapiTest-neo4j
    image: neo4j:5.16.0
    environment:
      - NEO4J_AUTH=neo4j/your_password_here  # Ensure the password is at least 8 characters
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs  # Optional
      - neo4j-conf:/conf  # Optional

volumes:
  db-data:
  neo4j-data:
  neo4j-logs:  # Optional
  neo4j-conf:  # Optional